---
# Secret
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: hardware
  name: hardware
  namespace: homework
type: Opaque
data:
  dbpass: WmFxMVhzdzJDZGUzCg==
  dbendpoint: aGFyZHdhcmVhdmFpbGFiaWxpdHkuYzl5czh2cXVnYzNrLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQo=